apiVersion: v1
kind: service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
    tire: web
    project: expense
  ports:
  - protocol: TCP
    port: 80
    targetPort: {{ .Values.configmap.port }}
```